/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembukuan;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import model.mdetailsawah;
import model.msawah;

/**
 *
 * @author ACER
 */
public class detailsawah extends javax.swing.JFrame {

    /**
     * Creates new form detailsawah
     */
    msawah msawah;
    mdetailsawah mdetailsawah;

    String datasawah[];
    String iddetailsawah;
    String idsawah;

    public detailsawah(String idsawah) {
        try {
            initComponents();
            this.idsawah = idsawah;
            msawah = new msawah();
            mdetailsawah = new mdetailsawah();
            datasawah = msawah.getsawwah(idsawah);
            txtnama.setText(datasawah[1]);
            updatetabel();
        } catch (SQLException ex) {
            Logger.getLogger(detailsawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updatetabel() throws SQLException {
        tabelkeluar.setModel(mdetailsawah.getdana("keluar", idsawah));
        tabelmasuk.setModel(mdetailsawah.getdana("masuk", idsawah));
        hapusno(tabelmasuk);
        hapusno(tabelkeluar);
        btnhapus.setEnabled(false);
        DefaultTableModel modelkeluar = (DefaultTableModel) tabelkeluar.getModel();
        DefaultTableModel modelmasuk = (DefaultTableModel) tabelmasuk.getModel();
        double uangkeluar = 0;
        double uangmasuk = 0;

        for (int i = 0; i < modelkeluar.getRowCount(); i++) {
            double getuang = Integer.parseInt(modelkeluar.getValueAt(i, 2).toString());
            uangkeluar += getuang;
        }
        for (int i = 0; i < modelmasuk.getRowCount(); i++) {
            double getuang = Integer.parseInt(modelmasuk.getValueAt(i, 2).toString());
            uangmasuk += getuang;
        }
        txtdanakeluar.setText(uangkeluar + "");
        txtdanamasuk.setText(uangmasuk + "");
keuntungan.setText((uangmasuk-uangkeluar)+"");
    }

    public void hapusno(JTable model) {
        TableColumn kolom = model.getColumnModel().getColumn(0);
        kolom.setMinWidth(0);
        kolom.setMaxWidth(0);
        kolom.setWidth(0);
        kolom.setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkeluar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelmasuk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtdanakeluar = new javax.swing.JLabel();
        txtdanamasuk = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inp_besar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inp_status = new javax.swing.JComboBox<>();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        inp_nama = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        inp_keterangan = new javax.swing.JTextArea();
        btnclear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        keuntungan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("nama sawah :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtnama.setText("nama sawah");
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        tabelkeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tabelkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelkeluar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 280, 350));

        tabelmasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tabelmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmasukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelmasuk);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 280, 350));

        jLabel1.setText("dana masuk");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 20));

        txtdanakeluar.setText("jLabel3");
        getContentPane().add(txtdanakeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 170, 20));

        txtdanamasuk.setText("jLabel3");
        getContentPane().add(txtdanamasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 170, 20));

        jLabel5.setText("total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, 20));

        jLabel6.setText("total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, 20));

        jLabel7.setText("dana keluar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 20));

        jLabel8.setText("keterangan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));
        getContentPane().add(inp_besar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, 30));

        jLabel9.setText("besar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel10.setText("dana");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        inp_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "keluar", "masuk" }));
        getContentPane().add(inp_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));

        btnhapus.setText("hapus");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel11.setText("nama");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));
        getContentPane().add(inp_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 30));

        inp_keterangan.setColumns(20);
        inp_keterangan.setRows(5);
        jScrollPane3.setViewportView(inp_keterangan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 250, 50));

        btnclear.setText("clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText("keuntungan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 20));

        keuntungan.setText("jLabel4");
        getContentPane().add(keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 180, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkeluarMouseClicked
        setdetailsawah(tabelkeluar);
        btnhapus.setEnabled(true);
    }//GEN-LAST:event_tabelkeluarMouseClicked
    public void setdetailsawah(JTable tabel) {
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        String id = model.getValueAt(tabel.getSelectedRow(), 0).toString();
        iddetailsawah = id;
        String detailsawah[] = mdetailsawah.getdetailsawah(id);

        inp_nama.setText(detailsawah[1]);
        inp_keterangan.setText(detailsawah[2]);
        inp_besar.setText(detailsawah[4]);
        if (detailsawah[3].equalsIgnoreCase("keluar")) {
            inp_status.setSelectedIndex(0);
        } else {
            inp_status.setSelectedIndex(1);
        }
        btnsimpan.setText("update");
    }
    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        try {
            if (btnsimpan.getText().equalsIgnoreCase("simpan")) {
                String data[] = {
                    idsawah,
                    inp_nama.getText(),
                    inp_keterangan.getText(),
                    inp_status.getSelectedItem().toString(),
                    inp_besar.getText()
                };
                mdetailsawah.tambahdetailsawah(data);
            } else {
                String data[] = {
                    iddetailsawah,
                    inp_nama.getText(),
                    inp_keterangan.getText(),
                    inp_status.getSelectedItem().toString(),
                    inp_besar.getText()
                };
                mdetailsawah.updatedetailsawah(data);
                btnsimpan.setText("update");
            }
            clear();
            updatetabel();
        } catch (SQLException ex) {
            Logger.getLogger(detailsawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed
    public void clear() {
        try {
            inp_nama.setText("");
            inp_besar.setText("");
            inp_keterangan.setText("");
            inp_status.setSelectedIndex(0);
            btnsimpan.setText("simpan");
            updatetabel();
        } catch (SQLException ex) {
            Logger.getLogger(detailsawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void tabelmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmasukMouseClicked
        setdetailsawah(tabelmasuk);
        btnhapus.setEnabled(true);
    }//GEN-LAST:event_tabelmasukMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            mdetailsawah.hapusdetailsawah(iddetailsawah);
            updatetabel();
        } catch (SQLException ex) {
            Logger.getLogger(detailsawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailsawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailsawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailsawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailsawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JTextField inp_besar;
    private javax.swing.JTextArea inp_keterangan;
    private javax.swing.JTextField inp_nama;
    private javax.swing.JComboBox<String> inp_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel keuntungan;
    private javax.swing.JTable tabelkeluar;
    private javax.swing.JTable tabelmasuk;
    private javax.swing.JLabel txtdanakeluar;
    private javax.swing.JLabel txtdanamasuk;
    private javax.swing.JLabel txtnama;
    // End of variables declaration//GEN-END:variables
}
