/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembukuan;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class sawah extends javax.swing.JFrame {

    /**
     * Creates new form sawah
     */
    model.msawah M_sawah;
    String piltanaman[];

    public sawah() {
        try {
            initComponents();
            M_sawah = new model.msawah();
            piltanaman = M_sawah.getlisttanaman();
            for (int i = 0; i < piltanaman.length; i++) {
                inp_jenistanaman.addItem(piltanaman[i]);
                System.out.println(piltanaman[i]);
            }
            tabel_sawah.setModel(M_sawah.getdatasawah());
        } catch (SQLException ex) {
            Logger.getLogger(sawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_sawah = new javax.swing.JTable();
        btndetail = new javax.swing.JButton();
        txt_namasawah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inp_namasawah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inp_hargasewa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inpalamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inp_jenissawah = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        inp_jenistanaman = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        inp_cari = new javax.swing.JTextField();
        idsawah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_sawah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_sawah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_sawahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_sawah);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 50, 560, 430));

        btndetail.setText("detail");
        btndetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetailActionPerformed(evt);
            }
        });
        getContentPane().add(btndetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        txt_namasawah.setText("nama sawah");
        getContentPane().add(txt_namasawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setText("nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));
        getContentPane().add(inp_namasawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 30));

        jLabel3.setText("jenis sawah");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));
        getContentPane().add(inp_hargasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 190, 30));

        jLabel4.setText("harga sewa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));
        getContentPane().add(inpalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 190, 30));

        jLabel5.setText("alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 30));

        inp_jenissawah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sewa", "pribadi" }));
        inp_jenissawah.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inp_jenissawahItemStateChanged(evt);
            }
        });
        getContentPane().add(inp_jenissawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 30));

        jLabel6.setText("jenis tanaman");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 30));

        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        inp_jenistanaman.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inp_jenistanamanItemStateChanged(evt);
            }
        });
        getContentPane().add(inp_jenistanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 30));

        jLabel1.setText("cari");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        inp_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inp_cariKeyReleased(evt);
            }
        });
        getContentPane().add(inp_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 230, -1));

        idsawah.setEnabled(false);
        getContentPane().add(idsawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        jLabel7.setText("id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        btnclear.setText("clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inp_jenissawahItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inp_jenissawahItemStateChanged
        if (inp_jenissawah.getSelectedItem().toString().equalsIgnoreCase("pribadi")) {
            inp_hargasewa.setEnabled(false);
            inp_hargasewa.setText("");
        } else {
            inp_hargasewa.setEnabled(true);
        }
    }//GEN-LAST:event_inp_jenissawahItemStateChanged

    private void inp_jenistanamanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inp_jenistanamanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inp_jenistanamanItemStateChanged

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (inp_namasawah.getText().equalsIgnoreCase("") || inpalamat.getText().equalsIgnoreCase("")) {

        } else {
            try {
                if (btnsimpan.getText().equalsIgnoreCase("simpan")) {
                    String data[] = {
                        inp_namasawah.getText(),
                        inp_hargasewa.getText(),
                        inpalamat.getText(),
                        inp_jenistanaman.getSelectedItem().toString()};
                    M_sawah.tambahsawah(data);
                }
                if (btnsimpan.getText().equalsIgnoreCase("update")) {
                    String data[] = {
                        idsawah.getText(),
                        inp_namasawah.getText(),
                        inp_hargasewa.getText(),
                        inpalamat.getText(),
                        inp_jenistanaman.getSelectedItem().toString()};
                    M_sawah.updatesawah(data);
                    btnsimpan.setText("simpan");
                }
                tabel_sawah.setModel(M_sawah.getdatasawah());
                clear();
            } catch (SQLException ex) {
                Logger.getLogger(sawah.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void inp_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inp_cariKeyReleased
        try {
            tabel_sawah.setModel(M_sawah.getdatasawah(inp_cari.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(sawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inp_cariKeyReleased

    private void tabel_sawahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_sawahMouseClicked
        int selectindex = tabel_sawah.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabel_sawah.getModel();

        idsawah.setText(model.getValueAt(selectindex, 0).toString());
        inp_namasawah.setText(model.getValueAt(selectindex, 1).toString());
        inp_hargasewa.setText(model.getValueAt(selectindex, 2).toString());
        inpalamat.setText(model.getValueAt(selectindex, 3).toString());
        int getindextanaman = 0;
        for (int i = 0; i < piltanaman.length; i++) {
            if (model.getValueAt(selectindex, 4).toString().equalsIgnoreCase(piltanaman[i])) {
                getindextanaman = i;
            }
        }
        inp_jenistanaman.setSelectedIndex(getindextanaman);
        btnsimpan.setText("update");
    }//GEN-LAST:event_tabel_sawahMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailActionPerformed
        try {
            detailsawah a = new detailsawah(idsawah.getText());
            a.setVisible(true);
        } catch (Exception e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_btndetailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void clear() {
        idsawah.setText("");
        inp_cari.setText("");
        inp_hargasewa.setText("");
        inp_jenissawah.setSelectedIndex(0);
        inp_jenistanaman.setSelectedIndex(0);
        inp_namasawah.setText("");
        inpalamat.setText("");
        btnsimpan.setText("simpan");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sawah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sawah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndetail;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JTextField idsawah;
    private javax.swing.JTextField inp_cari;
    private javax.swing.JTextField inp_hargasewa;
    private javax.swing.JComboBox<String> inp_jenissawah;
    private javax.swing.JComboBox<String> inp_jenistanaman;
    private javax.swing.JTextField inp_namasawah;
    private javax.swing.JTextField inpalamat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_sawah;
    private javax.swing.JLabel txt_namasawah;
    // End of variables declaration//GEN-END:variables
}
